
import psycopg2
import os

DB_HOST = "db.duqxgvnwmspxhftbjcxn.supabase.co"
DB_NAME = "postgres"
DB_USER = "postgres"
DB_PASS = "Ammuiuu#1008"
DB_PORT = "5432"

def init_db():
    print("Connecting to Supabase Postgres...")
    try:
        conn = psycopg2.connect(
            host=DB_HOST,
            database=DB_NAME,
            user=DB_USER,
            password=DB_PASS,
            port=DB_PORT
        )
        cur = conn.cursor()
        
        print("Creating table 'todos'...")
        cur.execute("""
            CREATE TABLE IF NOT EXISTS todos (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created_at TIMESTAMPTZ DEFAULT NOW(),
                name TEXT NOT NULL,
                is_complete BOOLEAN DEFAULT FALSE
            );
        """)
        
        print("Inserting sample data...")
        cur.execute("""
            INSERT INTO todos (name, is_complete)
            VALUES ('Setup Supabase Connection', TRUE),
                   ('Test Flask App', FALSE);
        """)
        
        conn.commit()
        cur.close()
        conn.close()
        print("✅ Database initialized successfully!")
        
    except Exception as e:
        print(f"❌ Database error: {e}")

if __name__ == "__main__":
    init_db()
